# Q1

In [1]:
import numpy as np

In [2]:
#a)
var1=np.arange(0,30)
print(var1)
print(var1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)


In [3]:
#b)
var2=var1.reshape((3,10))
print(var2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [4]:
#c)
var3=var2.reshape((2,5,3))
# or we can wrtie
#var3=var1.reshape((2,5,3))
print(var3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [5]:
var2[1][0]=-1
print(var2)
print(var3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [-1 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 -1 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [6]:
#  therefore reshape return a view not a copy

In [7]:
#e

In [8]:
sum_var3_2nddim=np.sum(var3,axis=2)
print(sum_var3_2nddim)

[[ 3 12 21 19 39]
 [48 57 66 75 84]]


In [9]:
sum_var3_0nddim=np.sum(var3,axis=0)
print(sum_var3_0nddim)

[[15 17 19]
 [21 23 25]
 [27 29 31]
 [33 24 37]
 [39 41 43]]


In [10]:
sum_var3_01nddim=np.sum(var3, axis=(0,1))
print(sum_var3_01nddim)

[135 134 155]


In [11]:
#f

In [12]:
print(var2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [-1 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [13]:
#row2=var2[2-1]
row2=var2[1]
print(row2)

[-1 11 12 13 14 15 16 17 18 19]


In [14]:
last_col=var2[:,-1]
print(last_col)

[ 9 19 29]


In [15]:
firstn_col=var2[:,0:3]
print(firstn_col)

[[ 0  1  2]
 [-1 11 12]
 [20 21 22]]


In [16]:
last_ncol=var2[:,-2::]
print(last_ncol)

[[ 8  9]
 [18 19]
 [28 29]]


In [17]:
right=var2[0:2:,-2::]
print(right)

[[ 8  9]
 [18 19]]


 # Q2  broadcasting


In [18]:
#used to perform operation on different size of arrays

In [19]:
arr1=np.array([1,2,3])

In [20]:
arr2=np.array([[3],[4],[5],[7]])
'''

arr2=np.array([3,4,5])
arr2=np.transpose(arr2)
print(arr2)

'''
print(arr2)

[[3]
 [4]
 [5]
 [7]]


In [21]:
sum=arr1*arr2
print(sum)

[[ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]
 [ 7 14 21]]


In [22]:
x1=3*sum
print(x1)

[[ 9 18 27]
 [12 24 36]
 [15 30 45]
 [21 42 63]]


In [23]:
#rough jst play around broadcasting

In [24]:
var3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, -1, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [25]:
x3=np.ones((5,3))
#x3=np.array([[1],[2],[3]])
#x3=np.array([[1,2,3]])

In [26]:
x2=var3+x3
print(x2)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10.  0. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]
  [28. 29. 30.]]]


In [27]:
vec1=np.arange(10)
print(vec1)


[0 1 2 3 4 5 6 7 8 9]


In [28]:
vec2=[[1]]
#sumvec=vec1+vec2
sumvec=1+vec1
print(sumvec)

[ 1  2  3  4  5  6  7  8  9 10]


In [29]:
vec3=sumvec.reshape(10,1)
print(vec3)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [30]:
#b)
A=sumvec+vec3
print(A)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [31]:
import numpy.random as npr

In [32]:
#data=np.exp(npr.randn(50,5))
data=np.exp(npr.rand(50,5))
print(data)

[[2.46941436 1.7783309  2.45197171 1.79124872 1.01454886]
 [1.96105758 2.04660136 1.34420124 2.15725686 1.20479382]
 [2.26742967 2.31095447 1.89447534 1.77722528 1.44340454]
 [2.39634161 1.77500128 1.21795268 1.31296081 2.08801917]
 [1.14924978 1.91228713 1.30634324 1.64335641 1.83397732]
 [1.52586759 2.01870121 2.39931107 1.11282518 1.4344737 ]
 [2.4320405  1.70575896 2.47309868 1.77318697 1.73433793]
 [1.85117816 1.90781841 1.40910189 1.74237832 1.36913851]
 [1.9754725  2.70700962 1.74469823 1.95545526 1.61068103]
 [1.66739252 1.71951638 2.54946531 1.12689421 1.09359876]
 [2.32479666 1.47374924 1.54602811 2.13472998 1.10063905]
 [1.39815557 2.45926608 1.72268937 2.47697962 1.15618871]
 [1.81415053 1.41698583 1.67426517 1.12604671 1.66258883]
 [1.26416262 2.29908167 2.66931757 1.22918804 1.72804741]
 [1.97702677 1.60088337 2.01989983 2.15022773 1.0095474 ]
 [1.39885409 1.45855689 2.11449357 2.36747041 1.17682012]
 [1.98029567 1.65196491 1.3492787  1.33950269 1.55327374]
 [1.31722151 1

In [33]:
temp=np.ones((1,50))
print(temp)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


In [34]:
means=(np.dot(temp,data))/50
print(means)

[[1.91390519 1.75123546 1.78705436 1.76050187 1.60931069]]


In [35]:
#method 2
tdata=np.transpose(data)
mean2=np.zeros(len(tdata))
std=np.zeros(len(tdata))
for i in range(len(tdata)):
    mean2[i]=np.mean(tdata[i])
    std[i]=np.std(tdata[i])
meanf=mean2.T
print(meanf)
print(std)

[1.91390519 1.75123546 1.78705436 1.76050187 1.60931069]
[0.47154887 0.43521788 0.48449141 0.52468298 0.45520194]


In [36]:
#method3
#print(data)
#i_col=data[:,1]
#print(i_col)

mean_col=np.zeros(len(data[0]))
std_col=np.zeros(len(data[0]))

for i in range(len(data[0])):
    i_col=data[:,i]
    mean_col[i]=np.mean(i_col)
    std_col[i]=np.std(i_col)
print(mean_col)
print(std_col)

[1.91390519 1.75123546 1.78705436 1.76050187 1.60931069]
[0.47154887 0.43521788 0.48449141 0.52468298 0.45520194]


In [37]:
#method4
mean_vec=np.mean(data,axis=0)
std_vec=np.std(data,axis=0)
print(mean_vec)
print(std_vec)

[1.91390519 1.75123546 1.78705436 1.76050187 1.60931069]
[0.47154887 0.43521788 0.48449141 0.52468298 0.45520194]


#z=(x-U)/sigma


In [40]:
#method1
normalised_data=(data-mean_vec)/std_vec
normalised_mean=np.mean(normalised_data,axis=0)
normalised_std=np.std(normalised_data,axis=0)
#print(normalised_data)
print(normalised_mean)
print(normalised_std)

[-1.28119737e-15 -1.90514271e-15 -7.34967642e-16  1.33670852e-15
 -9.04831765e-16]
[1. 1. 1. 1. 1.]


In [41]:
print(np.mean(normalised_mean))

-6.978861932793734e-16


In [42]:
# as we can see mean in each column is approx 0 and sd is 1


# vandermonde matrix

In [43]:
import numpy as np

In [44]:
def vandermonde(n):
    vec=np.arange(n)+1
    print(vec)
    tvec=vec.reshape((n,1))
    print(tvec)
    #vander=tvec**vec
    vander=vec**tvec
    vander=vander/vec
    #vander=vander.T
    vander=vander.astype(int)
    return vander


In [45]:
vander=vandermonde(12)
print(vander)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[         1          1          1          1          1          1
           1          1          1          1          1          1]
 [         1          2          3          4          5          6
           7          8          9         10         11         12]
 [         1          4          9         16         25         36
          49         64         81        100        121        144]
 [         1          8         27         64        125        216
         343        512        729       1000       1331       1728]
 [         1         16         81        256        625       1296
        2401       4096       6561      10000      14641      20736]
 [         1         32        243       1024       3125       7776
       16807      32768      59049     100000     161051     248832]
 [         1         64        729       4096      15625      46656

In [46]:
#by loop
def vandermonde1(n):
    vec=np.arange(n)+1
    print(vec)
    vec2=np.ones((n,n))
    for i in range(1,n):
        temp=vec2[i-1]*vec
        vec2[i]=temp
    print(vec2)

In [47]:
vandermonde1(5)

[1 2 3 4 5]
[[  1.   1.   1.   1.   1.]
 [  1.   2.   3.   4.   5.]
 [  1.   4.   9.  16.  25.]
 [  1.   8.  27.  64. 125.]
 [  1.  16.  81. 256. 625.]]


# vector matrix multiplication


In [48]:
import numpy as np
def matrix_multiplication(A,B):
    if len(A[0]) != len(B):
        print("not possible to multiply")
        return 
    m=len(A)
    p=len(B)
    n=len(B[0])
    mat=np.zeros((m,n))
    for i in range(m):       
        for j in range(n):
            for k in range(p):
                mat[i][j]+= A[i][k]*B[k][j]
            
    return mat
# time complexicity = m*n*p

In [49]:
#b
x=np.ones((12,1)).astype(int)
print(x)
print(vander)
b=matrix_multiplication(vander,x).astype(int)
print("product=",b.T)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]
[[         1          1          1          1          1          1
           1          1          1          1          1          1]
 [         1          2          3          4          5          6
           7          8          9         10         11         12]
 [         1          4          9         16         25         36
          49         64         81        100        121        144]
 [         1          8         27         64        125        216
         343        512        729       1000       1331       1728]
 [         1         16         81        256        625       1296
        2401       4096       6561      10000      14641      20736]
 [         1         32        243       1024       3125       7776
       16807      32768      59049     100000     161051     248832]
 [         1         64        729       4096      15625      46656
      117649     262144     531441    1000000    

In [50]:
#c
import numpy.linalg as nl
inv=nl.inv(vander).astype(int)
pro1=matrix_multiplication(inv,b).astype(int)
print(vander)
print(inv)
print(pro1)

[[         1          1          1          1          1          1
           1          1          1          1          1          1]
 [         1          2          3          4          5          6
           7          8          9         10         11         12]
 [         1          4          9         16         25         36
          49         64         81        100        121        144]
 [         1          8         27         64        125        216
         343        512        729       1000       1331       1728]
 [         1         16         81        256        625       1296
        2401       4096       6561      10000      14641      20736]
 [         1         32        243       1024       3125       7776
       16807      32768      59049     100000     161051     248832]
 [         1         64        729       4096      15625      46656
      117649     262144     531441    1000000    1771561    2985984]
 [         1        128       2187      1

In [51]:
print(nl.det(vander))

9.80551803726207e+49


In [52]:
#method2
bb=np.dot(vander,x)
print(bb)
pro2=np.dot(inv,bb)
print(pro2)

[[        12]
 [        78]
 [       650]
 [      6084]
 [     60710]
 [    630708]
 [   6735950]
 [  73399404]
 [  63706396]
 [ 402316366]
 [ 787518399]
 [-480708258]]
[[  -8976]
 [ -71104]
 [ 144804]
 [-153208]
 [  27202]
 [    572]
 [      0]
 [      0]
 [      0]
 [      0]
 [      0]
 [      0]]


In [53]:
# there is a difference in between values due to ill conditioned number

In [54]:
#d
print(vander)
print(b)
y=nl.solve(vander,b)
print(y)

[[         1          1          1          1          1          1
           1          1          1          1          1          1]
 [         1          2          3          4          5          6
           7          8          9         10         11         12]
 [         1          4          9         16         25         36
          49         64         81        100        121        144]
 [         1          8         27         64        125        216
         343        512        729       1000       1331       1728]
 [         1         16         81        256        625       1296
        2401       4096       6561      10000      14641      20736]
 [         1         32        243       1024       3125       7776
       16807      32768      59049     100000     161051     248832]
 [         1         64        729       4096      15625      46656
      117649     262144     531441    1000000    1771561    2985984]
 [         1        128       2187      1

In [55]:
# so we get y values approx equal to x values  by solve method of linalg